In [64]:
import numpy as np

In [65]:
# Arrays are used to store multiple values in one single variable
# Python does not have built-in support for Arrays, but Python Lists can be used instead, 
# but i will use numpy arrays for more "legitimate" arrays

def Arrays():
    # Each value in an array is a "0-Dimensional" array (scalar, element)
    global array1, array2, array3
    array1 = np.array([6, 7, 8, 6, 4, 2, 5, 9, 7, 3], dtype="f") # Creates an 1 dimensional -array with 10 elements and float datatype
    array2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]) # 2 dimensional -array with 2rows and 5cols, so essentially a 2x5 matrix
    array3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # 3 dimensional -array with 2rows, 2cols, and 3 depth (x, y, z), often used to represent a 3rd order tensor

def ArrayInfo():
    # Prints the array, checks its type, datatype, shape and tells us how many dimensions the array has
    print("Arrays, types, datatypes, shapes, and dimensions:")
    print(array1, type(array1), array1.dtype, array1.shape, array1.ndim, "\n")
    print(array2, type(array2), array2.dtype, array2.shape, array2.ndim, "\n")
    print(array3, type(array3), array3.dtype, array3.shape, array3.ndim, "\n")

def ArrayAccess():
    # Accessing elements in an array
    print("Accessing elements in an array:")
    print(" First element of array1:", array1[0], "\n", "Second element of the first column of array2:", array2[0, 1], "\n", "Third element of the first row of the second matrix of array3:", array3[1, 0, 2],"\n")

def ArraySlicing():
    # Slicing arrays, step is defaulted to 1 if not specified
    print("Slicing arrays:")
    print("\n", "Elements from index 1 to 5 with a step of 2 of array1:", array1[1:5:2], "\n", "Elements from index 1 to 4 of first column of array2:", array2[0, 1:4], "\n")

def CopiesAndViews():
    # Copies and views, a copy owns the data and any changes made to the copy will not affect the original array, 
    # a view does not own the data and any changes made to the view will affect the original array
    print("Copies and views:")
    array1_copy = array1.copy()
    array1_view = array1.view()
    array1[0] = 22.2 # Changes the first element of array1
    print("Copy of array1:", array1_copy, "\n") # The first element of the copy is still 6
    print("View of array1:", array1_view, "\n") # The first element of the view is now 22.2
    array1[0] = 6 # Changes the first element of array1 back to 6

def ArrayMethods():
    # Methods for arrays
    print("Methods for arrays:")
    print("Sum of array1:", array1.sum(), "\n", "Minimum value of array2:", array2.min(), "\n", "Maximum value of array3:", array3.max(), "\n")
    
def ArrayReshaping():
    # Reshaping arrays, changing the number of rows and columns
    print("Reshaping arrays:")
    print("Reshaped array1:", array1.reshape(2, 5)) # Reshapes array1 to 2x5 matrix

In [66]:
ArrayInfo()

Arrays, types, datatypes, shapes, and dimensions:
[22.2  7.   8.   6.   4.   2.   5.   9.   7.   3. ] <class 'numpy.ndarray'> float32 (10,) 1 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] <class 'numpy.ndarray'> int32 (2, 5) 2 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] <class 'numpy.ndarray'> int32 (2, 2, 3) 3 



In [67]:
ArrayAccess()

Accessing elements in an array:
 First element of array1: 22.2 
 Second element of the first column of array2: 2 
 Third element of the first row of the second matrix of array3: 9 



In [68]:
ArraySlicing()

Slicing arrays:

 Elements from index 1 to 5 with a step of 2 of array1: [7. 6.] 
 Elements from index 1 to 4 of first column of array2: [2 3 4] 



In [69]:
CopiesAndViews() #TODO global variables mess with copies and views

Copies and views:
Copy of array1: [22.2  7.   8.   6.   4.   2.   5.   9.   7.   3. ] 

View of array1: [22.2  7.   8.   6.   4.   2.   5.   9.   7.   3. ] 



In [70]:
ArrayMethods()

Methods for arrays:
Sum of array1: 57.0 
 Minimum value of array2: 1 
 Maximum value of array3: 12 



In [71]:
ArrayReshaping()

Reshaping arrays:
Reshaped array1: [[6. 7. 8. 6. 4.]
 [2. 5. 9. 7. 3.]]
