In [5]:
import numpy as np

In [9]:
# Arrays are used to store multiple values in one single variable
# Python does not have built-in support for Arrays, but Python Lists can be used instead, 
# but i will use numpy arrays for more "legitimate" arrays

def Arrays():
    # Each value in an array is a "0-Dimensional" array (scalar, element)
    array1 = np.array([6, 7, 8, 6, 4, 2, 5, 9, 7, 3], dtype="f") # Creates an 1 dimensional -array with 10 elements and float datatype
    array2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]) # 2 dimensional -array with 2rows and 5cols, so essentially a 2x5 matrix
    array3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # 3 dimensional -array with 2rows, 2cols, and 3 depth (x, y, z), often used to represent a 3rd order tensor

    # Prints the array, checks its type, datatype, shape and tells us how many dimensions the array has
    print("Arrays, types, datatypes, shapes, and dimensions:")
    print(array1, type(array1), array1.dtype, array1.shape, array1.ndim, "\n")
    print(array2, type(array2), array2.dtype, array2.shape, array2.ndim, "\n")
    print(array3, type(array3), array3.dtype, array3.shape, array3.ndim, "\n")


    # Accessing elements in an array
    print("Accessing elements in an array:")
    print(" First element of array1:", array1[0], "\n", "Second element of the first column of array2:", array2[0, 1], "\n", "Third element of the first row of the second matrix of array3:", array3[1, 0, 2],"\n")

    # Slicing arrays, step is defaulted to 1 if not specified
    print("Slicing arrays:")
    print("\n", "Elements from index 1 to 5 with a step of 2 of array1:", array1[1:5:2], "\n", "Elements from index 1 to 4 of first column of array2:", array2[0, 1:4], "\n")

    # Copies and views, a copy owns the data and any changes made to the copy will not affect the original array, 
    # a view does not own the data and any changes made to the view will affect the original array
    print("Copies and views:")
    array1_copy = array1.copy()
    array1_view = array1.view()
    array1[0] = 22.2 # Changes the first element of array1
    print("Copy of array1:", array1_copy, "\n") # The first element of the copy is still 6
    print("View of array1:", array1_view, "\n") # The first element of the view is now 22.2
    array1[0] = 6 # Changes the first element of array1 back to 6

    # Methods for arrays
    print("Methods for arrays:")
    print("Sum of array1:", array1.sum(), "\n", "Minimum value of array2:", array2.min(), "\n", "Maximum value of array3:", array3.max(), "\n")
    
    # Reshaping arrays, changing the number of rows and columns
    print("Reshaping arrays:")
    print("Reshaped array1:", array1.reshape(2, 5)) # Reshapes array1 to 2x5 matrix
    
Arrays()
# There are many more things you can do with arrays, here are just some demonstrated.

Arrays, types, datatypes, shapes, and dimensions:
[6. 7. 8. 6. 4. 2. 5. 9. 7. 3.] <class 'numpy.ndarray'> float32 (10,) 1 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] <class 'numpy.ndarray'> int32 (2, 5) 2 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] <class 'numpy.ndarray'> int32 (2, 2, 3) 3 

Accessing elements in an array:
 First element of array1: 6.0 
 Second element of the first column of array2: 2 
 Third element of the first row of the second matrix of array3: 9 

Slicing arrays:

 Elements from index 1 to 5 with a step of 2 of array1: [7. 6.] 
 Elements from index 1 to 4 of first column of array2: [2 3 4] 

Copies and views:
Copy of array1: [6. 7. 8. 6. 4. 2. 5. 9. 7. 3.] 

View of array1: [22.2  7.   8.   6.   4.   2.   5.   9.   7.   3. ] 

Methods for arrays:
Sum of array1: 57.0 
 Minimum value of array2: 1 
 Maximum value of array3: 12 

Reshaping arrays:
Reshaped array1: [[6. 7. 8. 6. 4.]
 [2. 5. 9. 7. 3.]]


In [32]:
# Linked-lists are similar to arrays, they are a collection of nodes that are linked with each other.

# Creating a class for the list nodes, each node has some sort of data and a reference to another node.
class node:
    def __init__(self, data):
        self.data = data
        self.next = None
        
class LinkedList:
    def __init__(self, head = None):
        # Head = the first (top) node of the list
        self.head = head
    
    # Method for adding a node at the begin of Linked List
    def InsAtBegin(self, data):
        new_node = node(data)
        if self.head is None:
            self.head = new_node
            return
        else:
            new_node.next = self.head
            self.head = new_node
            
    # Method for adding a node at the end of the linked list        
    def InsAtEnd(self, data):
        new_node = node(data)
        if self.head is None:
            self.head = new_node
            return
        
        current_node = self.head
        
        while(current_node.next):
            current_node = current_node.next
        
        current_node.next = new_node
    
    # Updating a node value at given index
    def UpdateNode(self, value, index):
        current_node = self.head
        pos = 0
        if pos == index:
            current_node.data = value
        else:
            while(current_node != None and pos != index):
                pos += 1
                current_node = current_node.next
                
            if current_node != None:
                current_node.data = value
            else:
                print("Index not found")
                
    # Removes first node, making the second one head of the list   
    def RemoveFirst(self):
        if (self.head == None):
            return
        self.head = self.head.next
        
    def RemoveLast(self):
        if self.head is None:
            return
        
        current_node = self.head
        while (current_node.next.next): # Iterates to the second last node, so if next has a next then we continue
            current_node = current_node.next
        current_node.next = None # And when we no longer have 2 nexts, then set the last node to None
        
    def printList(self):
        current_node = self.head
        while(current_node): # Iterates through the list until current_node is None
            print(current_node.data)
            current_node = current_node.next

# Creating a linked list
l_list = LinkedList()

# Adding nodes to the linked list
l_list.InsAtBegin('a')
l_list.InsAtEnd('d')
l_list.InsAtEnd('f')
l_list.InsAtBegin('p')
l_list.InsAtBegin('k')
l_list.InsAtEnd('y')
l_list.InsAtBegin('s')
l_list.InsAtBegin('n')

# Printing the list
print("Node data at initial creation:")
l_list.printList()

# Node removal
l_list.RemoveFirst()
l_list.RemoveLast()

print("\nLinked list after removing nodes:")
l_list.printList()

l_list.UpdateNode('abc', 3) 
print("\nLinked list after updating a node:")
l_list.printList()

#HACK maybe implement node insert at index and removal at index later, but updating seems to cause enough challenges for now 

Node data at initial creation:
n
s
k
p
a
d
f
y

Linked list after removing nodes:
s
k
p
a
d
f

Linked list after updating a node:
s
k
p
abc
d
f
